trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'seu-usuario/mobead'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
